delete:
  description: Deletes a call control application.
  operationId: deleteCallControlApplication
  parameters:
    - description: Identifies the resource.
      in: path
      name: id
      required: true
      schema:
        example: '1293384261075731499'
        format: int64
        type: string
  responses:
    '200':
      $ref: ../components/responses/CallControlApplicationResponse.yaml
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yaml
    '404':
      description: Resource not found
    '422':
      description: Bad request
  summary: Delete a call control application
  tags:
    - Call Control Applications
  x-latency-category: interactive
get:
  description: Retrieves the details of an existing call control application.
  operationId: retrieveCallControlApplication
  parameters:
    - description: Identifies the resource.
      in: path
      name: id
      required: true
      schema:
        example: '1293384261075731499'
        format: int64
        type: string
  responses:
    '200':
      $ref: ../components/responses/CallControlApplicationResponse.yaml
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yaml
    '404':
      description: Resource not found
    '422':
      description: Bad request
  summary: Retrieve a call control application
  tags:
    - Call Control Applications
  x-latency-category: interactive
patch:
  description: Updates settings of an existing call control application.
  operationId: updateCallControlApplication
  parameters:
    - description: Identifies the resource.
      in: path
      name: id
      required: true
      schema:
        example: '1293384261075731499'
        format: int64
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/UpdateCallControlApplicationRequest.yaml
    description: Update call control application request.
    required: true
  responses:
    '200':
      $ref: ../components/responses/CallControlApplicationResponse.yaml
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yaml
    '404':
      description: Resource not found
    '422':
      description: Bad request
  summary: Update a call control application
  tags:
    - Call Control Applications
  x-latency-category: interactive
