get:
  description: Return a list of call control applications.
  operationId: listCallControlApplications
  parameters:
    - $ref: ../components/parameters/PageNumber.yaml
    - $ref: ../components/parameters/PageSize.yaml
    - $ref: ../components/parameters/FilterApplicationName.yaml
    - $ref: ../components/parameters/FilterOutboundVoiceProfileId.yaml
    - $ref: ../components/parameters/SortConnection.yaml
  responses:
    '200':
      $ref: ../components/responses/ListCallControlApplicationsResponse.yaml
    '400':
      description: Bad request
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yaml
    '404':
      description: Resource not found
  summary: List call control applications
  tags:
    - Call Control Applications
  x-endpoint-cost: medium
  x-group-parameters: 'true'
  x-latency-category: interactive
post:
  description: Create a call control application.
  operationId: createCallControlApplication
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CreateCallControlApplicationRequest.yaml
    description: Create call control application request.
    required: true
  responses:
    '201':
      $ref: ../components/responses/CallControlApplicationResponse.yaml
    '422':
      description: Bad Request
  summary: Create a call control application
  tags:
    - Call Control Applications
  x-endpoint-cost: medium
  x-latency-category: interactive
