get:
  description: >-
    This endpoint returns a list of your Fax Applications inside the 'data'
    attribute of the response. You can adjust which applications are listed by
    using filters. Fax Applications are used to configure how you send and
    receive faxes using the Programmable Fax API with Telnyx.
  operationId: listFaxApplications
  parameters:
    - $ref: ../components/parameters/PageNumber.yaml
    - $ref: ../components/parameters/PageSize.yaml
    - $ref: ../components/parameters/FilterApplicationName.yaml
    - $ref: ../components/parameters/FilterOutboundVoiceProfileId.yaml
    - $ref: ../components/parameters/SortConnection.yaml
  responses:
    '200':
      $ref: ../components/responses/GetAllFaxApplicationsResponse.yaml
    '400':
      description: Bad request
    '401':
      description: Unauthorized
    '404':
      description: Resource not found
  summary: List all Fax Applications
  tags:
    - Programmable Fax Applications
  x-endpoint-cost: medium
  x-latency-category: responsive
post:
  description: >-
    Creates a new Fax Application based on the parameters sent in the request.
    The application name and webhook URL are required. Once created, you can
    assign phone numbers to your application using the `/phone_numbers`
    endpoint.
  operationId: CreateFaxApplication
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CreateFaxApplicationRequest.yaml
    description: Parameters that can be set when creating a Fax Application
    required: true
  responses:
    '201':
      $ref: ../components/responses/FaxApplicationResponse.yaml
    '422':
      description: Bad request
  summary: Creates a Fax Application
  tags:
    - Programmable Fax Applications
  x-endpoint-cost: medium
  x-latency-category: responsive
