delete:
  description: >-
    Permanently deletes a Fax Application. Deletion may be prevented if the
    application is in use by phone numbers.
  operationId: DeleteFaxApplication
  parameters:
    - $ref: ../components/parameters/id.yaml
  responses:
    '200':
      $ref: ../components/responses/FaxApplicationResponse.yaml
    '401':
      description: Unauthorized
    '404':
      description: Resource not found
    '422':
      description: Bad request
  summary: Deletes a Fax Application
  tags:
    - Programmable Fax Applications
  x-latency-category: responsive
get:
  description: >-
    Return the details of an existing Fax Application inside the 'data'
    attribute of the response.
  operationId: getFaxApplication
  parameters:
    - $ref: ../components/parameters/id.yaml
  responses:
    '200':
      $ref: ../components/responses/FaxApplicationResponse.yaml
    '401':
      description: Unauthorized
    '404':
      description: Resource not found
    '422':
      description: Bad request
  summary: Retrieve a Fax Application
  tags:
    - Programmable Fax Applications
  x-latency-category: responsive
patch:
  description: >-
    Updates settings of an existing Fax Application based on the parameters of
    the request.
  operationId: UpdateFaxApplication
  parameters:
    - $ref: ../components/parameters/id.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/UpdateFaxApplicationRequest.yaml
    description: Parameters to be updated for the Fax Application
    required: true
  responses:
    '200':
      $ref: ../components/responses/FaxApplicationResponse.yaml
    '401':
      description: Unauthorized
    '404':
      description: Resource not found
    '422':
      description: Bad request
  summary: Update a Fax Application
  tags:
    - Programmable Fax Applications
  x-latency-category: responsive
