get:
  description: >-
    Retrieves push credentials for a given mobile application based on filters
    for a user
  operationId: getPushCredentials
  parameters:
    - description: The unique identifier of a mobile application
      in: path
      name: mobile_application_id
      required: true
      schema:
        example: 0ccc7b54-4df3-4bca-a65a-3da1ecc777f0
        format: uuid
        type: string
    - description: ISO 8601 date for filtering credentials created on that date
      in: query
      name: filter[created_at][eq]
      schema:
        example: '2021-04-25'
        format: date
        type: string
    - description: ISO 8601 date for filtering credentials created after that date
      in: query
      name: filter[created_at][gte]
      schema:
        example: '2021-04-25'
        format: date
        type: string
    - description: ISO 8601 date for filtering credentials created before that date
      in: query
      name: filter[created_at][lte]
      schema:
        example: '2021-04-25'
        format: date
        type: string
    - description: Unique push credential alias
      in: query
      name: filter[alias]
      schema:
        example: LucyCredential
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            items:
              $ref: ../components/schemas/PushCredentialResponse.yaml
            type: array
      description: Mobile application created
    '401':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unauthorized request
    '422':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unable to process request
  summary: Retrieves push credentials associated to a mobile application
  tags:
    - Push Credentials
  x-latency-category: responsive
post:
  description: Creates a new credential for a given mobile application
  operationId: addPushCredential
  parameters:
    - description: The unique identifier of a mobile application
      in: path
      name: mobile_application_id
      required: true
      schema:
        example: 0ccc7b54-4df3-4bca-a65a-3da1ecc777f0
        format: uuid
        type: string
  requestBody:
    content:
      application/json:
        schema:
          oneOf:
            - $ref: ../components/schemas/CreateIosPushCredentialRequest.yaml
            - $ref: ../components/schemas/CreateAndroidPushCredentialRequest.yaml
    description: Push credential parameters that need to be sent in the request
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PushCredentialResponse.yaml
      description: Push credential created
    '401':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unauthorized request
    '422':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unable to process request
  summary: Adds push credential to a given mobile application
  tags:
    - Mobile Applications
  x-latency-category: responsive
