get:
  description: Retrieves all mobile applications for a user
  operationId: getAllMobileApplications
  responses:
    '200':
      content:
        application/json:
          schema:
            items:
              $ref: ../components/schemas/MobileApplicationResponse.yaml
            type: array
      description: Mobile application created
    '401':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unauthorized request
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Resource not found
    '422':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unable to process request
  summary: Retrieves mobile applications
  tags:
    - Mobile Applications
  x-latency-category: responsive
post:
  description: >-
    Creates a new mobile application which can be android or ios based on the
    `type` parameter
  operationId: addMobileApplication
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CreateMobileApplicationRequest.yaml
    description: Mobile application parameters that need to be sent in the request
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/MobileApplicationResponse.yaml
      description: Mobile application created
    '401':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unauthorized request
    '422':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Errors.yaml
      description: Unable to process request
  summary: Adds a mobile application
  tags:
    - Mobile Applications
  x-latency-category: responsive
