delete:
  description: Delete a notification setting.
  operationId: deleteNotificationSetting
  parameters:
    - $ref: ../components/parameters/Id.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            properties:
              data:
                $ref: ../components/schemas/NotificationSetting.yaml
            type: object
      description: A Notification Setting response
    '201':
      content:
        application/json:
          schema:
            properties:
              data:
                $ref: ../components/schemas/NotificationSetting.yaml
            type: object
      description: A Notification Setting response - async
    default:
      $ref: ../components/responses/GenericErrorResponse.yaml
  summary: Delete a notification setting
  tags:
    - Notifications
  x-latency-category: responsive
get:
  description: Retrieve a notification setting.
  operationId: retrieveNotificationSetting
  parameters:
    - $ref: ../components/parameters/Id.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            properties:
              data:
                $ref: ../components/schemas/NotificationSetting.yaml
            type: object
      description: A Notification Setting response
    default:
      $ref: ../components/responses/GenericErrorResponse.yaml
  summary: Retrieve a notification setting
  tags:
    - Notifications
  x-latency-category: responsive
