post:
  description: >-
    Creates a background job to update the emergency settings of a collection of
    phone numbers. At most one thousand numbers can be updated per API call.
  operationId: createPhoneNumbersJobUpdateEmergencySettings
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/PhoneNumbersJobUpdateEmergencySettingsRequest.yaml
    required: true
  responses:
    '202':
      content:
        application/json:
          schema:
            properties:
              data:
                $ref: ../components/schemas/PhoneNumbersJob.yaml
            title: Phone Numbers Enable Emergency
            type: object
      description: Phone numbers enable emergency requested.
    default:
      $ref: ../components/responses/GenericErrorResponse.yaml
  summary: Update the emergency settings from a batch of numbers
  tags:
    - Number Background Jobs
  x-latency-category: background
