get:
  description: List all requirements with filtering, sorting, and pagination
  operationId: listRequirements
  parameters:
    - $ref: ../components/parameters/DocReqsCountryFilter.yaml
    - $ref: ../components/parameters/DocReqsPhoneNumberTypeFilter.yaml
    - $ref: ../components/parameters/DocReqsActionFilter.yaml
    - $ref: ../components/parameters/DocReqsRequirementsSort.yaml
    - $ref: ../components/parameters/PageNumber.yaml
    - $ref: ../components/parameters/PageSize.yaml
  responses:
    '200':
      $ref: ../components/responses/ListRequirementsResponse.yaml
    default:
      $ref: ../components/responses/GenericErrorResponse.yaml
  summary: List all requirements
  tags:
    - Requirements
  x-latency-category: responsive
