get:
  description: Returns a list of your TeXML Applications.
  operationId: findTexmlApplications
  parameters:
    - $ref: ../components/parameters/PageNumber.yaml
    - $ref: ../components/parameters/PageSize.yaml
    - description: >-
        If present, applications with <code>friendly_name</code> containing the
        given value will be returned. Matching is not case-sensitive. Requires
        at least three characters.
      in: query
      name: filter[friendly_name][contains]
      schema:
        default: 'null'
        type: string
    - $ref: ../components/parameters/FilterOutboundVoiceProfileId.yaml
    - $ref: ../components/parameters/SortConnection.yaml
  responses:
    '200':
      $ref: ../components/responses/GetAllTexmlApplicationsResponse.yaml
    '400':
      description: Bad request
    '401':
      description: Unauthorized
    '404':
      description: Resource not found
  summary: List all TeXML Applications
  tags:
    - TeXML Applications
  x-endpoint-cost: medium
  x-latency-category: responsive
post:
  description: Creates a TeXML Application.
  operationId: CreateTexmlApplication
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CreateTexmlApplicationRequest.yaml
    description: Parameters that can be set when creating a TeXML Application
    required: true
  responses:
    '201':
      $ref: ../components/responses/TexmlApplicationResponse.yaml
    '422':
      description: Bad request
  summary: Creates a TeXML Application
  tags:
    - TeXML Applications
  x-endpoint-cost: medium
  x-latency-category: responsive
