content:
  application/json:
    schema:
      properties:
        data:
          items:
            $ref: ../schemas/TexmlApplication.yaml
          type: array
        meta:
          $ref: ../schemas/PaginationMeta.yaml
      title: Get All Texml Applications Response
      type: object
description: Successful response
