content:
  application/json:
    schema:
      properties:
        data:
          items:
            $ref: ../schemas/PhoneNumberWithMessagingSettings.yaml
          type: array
        meta:
          $ref: ../schemas/PaginationMeta.yaml
      title: List Messaging Settings Response
      type: object
description: Successful response with a list of phone numbers with messaging settings.
