content:
  application/json:
    schema:
      properties:
        data:
          items:
            $ref: ../schemas/PhoneNumberWithVoiceSettings.yaml
          type: array
        meta:
          $ref: ../schemas/PaginationMeta.yaml
      title: List Phone Numbers With Voice Settings Response
      type: object
description: Successful response with a list of phone numbers with voice settings.
