content:
  application/json:
    schema:
      properties:
        data:
          $ref: ../schemas/PhoneNumberWithVoiceSettings.yaml
      title: Retrieve Phone Number Voice Response
      type: object
description: >-
  Successful response with details about a phone number including voice
  settings.
