content:
  application/json:
    schema:
      properties:
        data:
          $ref: ../schemas/PhoneNumberWithMessagingSettings.yaml
      title: Retrieve Messaging Settings Response
      type: object
description: >-
  Successful response with details about a phone number including voice
  settings.
