# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/openapi.yaml:
  info-license-url:
    - '#/info/license/url'
  no-ambiguous-paths:
    - '#/paths/~1phone_numbers~1{id}~1messaging'
    - '#/paths/~1phone_numbers~1{id}~1voice'
  no-unresolved-refs:
    - '#/paths/~1access_fqdns'
    - '#/paths/~1access_fqdns~1{fqdn_id}'
    - '#/paths/~1access_fqdns~1{fqdn_id}~1ips'
    - '#/paths/~1access_ip_address'
    - '#/paths/~1access_ip_address~1{access_ip_address_id}'
    - '#/paths/~1access_ip_ranges'
    - '#/paths/~1access_ip_ranges~1{access_ip_range_id}'
    - '#/paths/~1actions~1bulk~1telephony_credentials'
    - '#/paths/~1actions~1network_preferences~1sim_cards'
    - '#/paths/~1actions~1register~1sim_cards'
    - '#/paths/~1actions~1{action}~1telephony_credentials'
    - '#/paths/~1authentication_providers'
    - '#/paths/~1authentication_providers~1{id}'
    - '#/paths/~1available_phone_number_blocks'
    - '#/paths/~1available_phone_numbers'
    - '#/paths/~1balance'
    - '#/paths/~1billing_groups'
    - '#/paths/~1billing_groups~1{id}'
    - '#/paths/~1bulk_sim_card_actions'
    - '#/paths/~1bulk_sim_card_actions~1{id}'
    - '#/paths/~1business_identities'
    - '#/paths/~1business_identities~1{id}'
    - '#/paths/~1call_control_applications'
    - '#/paths/~1call_control_applications~1{id}'
    - '#/paths/~1call_events'
    - '#/paths/~1calls'
    - '#/paths/~1calls~1register'
    - '#/paths/~1calls~1{call_control_id}'
    - '#/paths/~1calls~1{call_control_id}~1actions~1answer'
    - '#/paths/~1calls~1{call_control_id}~1actions~1bridge'
    - '#/paths/~1calls~1{call_control_id}~1actions~1client_state_update'
    - '#/paths/~1calls~1{call_control_id}~1actions~1enqueue'
    - '#/paths/~1calls~1{call_control_id}~1actions~1fork_start'
    - '#/paths/~1calls~1{call_control_id}~1actions~1fork_stop'
    - '#/paths/~1calls~1{call_control_id}~1actions~1gather'
    - '#/paths/~1calls~1{call_control_id}~1actions~1gather_stop'
    - '#/paths/~1calls~1{call_control_id}~1actions~1gather_using_audio'
    - '#/paths/~1calls~1{call_control_id}~1actions~1gather_using_speak'
    - '#/paths/~1calls~1{call_control_id}~1actions~1hangup'
    - '#/paths/~1calls~1{call_control_id}~1actions~1leave_queue'
    - '#/paths/~1calls~1{call_control_id}~1actions~1playback_start'
    - '#/paths/~1calls~1{call_control_id}~1actions~1playback_stop'
    - '#/paths/~1calls~1{call_control_id}~1actions~1record_pause'
    - '#/paths/~1calls~1{call_control_id}~1actions~1record_resume'
    - '#/paths/~1calls~1{call_control_id}~1actions~1record_start'
    - '#/paths/~1calls~1{call_control_id}~1actions~1record_stop'
    - '#/paths/~1calls~1{call_control_id}~1actions~1refer'
    - '#/paths/~1calls~1{call_control_id}~1actions~1reject'
    - '#/paths/~1calls~1{call_control_id}~1actions~1send_dtmf'
    - '#/paths/~1calls~1{call_control_id}~1actions~1speak'
    - '#/paths/~1calls~1{call_control_id}~1actions~1streaming_start'
    - '#/paths/~1calls~1{call_control_id}~1actions~1streaming_stop'
    - '#/paths/~1calls~1{call_control_id}~1actions~1transcription_start'
    - '#/paths/~1calls~1{call_control_id}~1actions~1transcription_stop'
    - '#/paths/~1calls~1{call_control_id}~1actions~1transfer'
    - '#/paths/~1channel_zones'
    - '#/paths/~1channel_zones~1{channel_zone_id}'
    - '#/paths/~1channel_zones~1{channel_zone_id}~1channel_zone_phone_numbers'
    - >-
      #/paths/~1channel_zones~1{channel_zone_id}~1channel_zone_phone_numbers~1{phone_number}
    - '#/paths/~1comments'
    - '#/paths/~1comments~1{id}'
    - '#/paths/~1comments~1{id}~1read'
    - '#/paths/~1conferences'
    - '#/paths/~1conferences~1{conference_id}~1participants'
    - '#/paths/~1conferences~1{id}'
    - '#/paths/~1conferences~1{id}~1actions~1dial_participant'
    - '#/paths/~1conferences~1{id}~1actions~1hold'
    - '#/paths/~1conferences~1{id}~1actions~1join'
    - '#/paths/~1conferences~1{id}~1actions~1leave'
    - '#/paths/~1conferences~1{id}~1actions~1mute'
    - '#/paths/~1conferences~1{id}~1actions~1play'
    - '#/paths/~1conferences~1{id}~1actions~1record_start'
    - '#/paths/~1conferences~1{id}~1actions~1record_stop'
    - '#/paths/~1conferences~1{id}~1actions~1speak'
    - '#/paths/~1conferences~1{id}~1actions~1stop'
    - '#/paths/~1conferences~1{id}~1actions~1unhold'
    - '#/paths/~1conferences~1{id}~1actions~1unmute'
    - '#/paths/~1conferences~1{id}~1actions~1update'
    - '#/paths/~1connections'
    - '#/paths/~1connections~1{id}'
    - '#/paths/~1credential_connections'
    - '#/paths/~1credential_connections~1{id}'
    - '#/paths/~1custom_storage_credentials~1{connection_id}'
    - '#/paths/~1customer_service_requests'
    - '#/paths/~1customer_service_requests~1phone_number_coverages'
    - '#/paths/~1customer_service_requests~1{customer_service_request_id}'
    - '#/paths/~1detail_records'
    - '#/paths/~1dialogflow_connections~1{connection_id}'
    - '#/paths/~1document_links'
    - '#/paths/~1documents'
    - '#/paths/~1documents~1{id}'
    - '#/paths/~1documents~1{id}~1download'
    - '#/paths/~1dynamic_emergency_addresses'
    - '#/paths/~1dynamic_emergency_addresses~1{id}'
    - '#/paths/~1dynamic_emergency_endpoints'
    - '#/paths/~1dynamic_emergency_endpoints~1{id}'
    - '#/paths/~1fax_applications'
    - '#/paths/~1fax_applications~1{id}'
    - '#/paths/~1faxes'
    - '#/paths/~1faxes~1{id}'
    - '#/paths/~1faxes~1{id}~1actions~1cancel'
    - '#/paths/~1faxes~1{id}~1actions~1refresh'
    - '#/paths/~1fqdn_connections'
    - '#/paths/~1fqdn_connections~1{id}'
    - '#/paths/~1fqdns'
    - '#/paths/~1fqdns~1{id}'
    - '#/paths/~1inventory_coverage'
    - '#/paths/~1ip_connections'
    - '#/paths/~1ip_connections~1{id}'
    - '#/paths/~1ips'
    - '#/paths/~1ips~1{id}'
    - '#/paths/~1ledger_billing_group_reports'
    - '#/paths/~1ledger_billing_group_reports~1{id}'
    - '#/paths/~1managed_accounts'
    - '#/paths/~1managed_accounts~1{id}'
    - '#/paths/~1managed_accounts~1{id}~1actions~1disable'
    - '#/paths/~1managed_accounts~1{id}~1actions~1enable'
    - '#/paths/~1media'
    - '#/paths/~1media~1{media_name}'
    - '#/paths/~1media~1{media_name}~1download'
    - '#/paths/~1messages'
    - '#/paths/~1messages~1long_code'
    - '#/paths/~1messages~1number_pool'
    - '#/paths/~1messages~1short_code'
    - '#/paths/~1messages~1{id}'
    - '#/paths/~1messaging_hosted_number_orders'
    - '#/paths/~1messaging_hosted_number_orders~1{id}'
    - '#/paths/~1messaging_hosted_number_orders~1{id}~1actions~1file_upload'
    - '#/paths/~1messaging_hosted_numbers~1{id}'
    - '#/paths/~1messaging_profile_metrics'
    - '#/paths/~1messaging_profiles'
    - '#/paths/~1messaging_profiles~1{id}'
    - '#/paths/~1messaging_profiles~1{id}~1metrics'
    - '#/paths/~1messaging_profiles~1{id}~1phone_numbers'
    - '#/paths/~1messaging_profiles~1{id}~1short_codes'
    - '#/paths/~1messaging_url_domains'
    - '#/paths/~1mobile_applications'
    - '#/paths/~1mobile_applications~1{mobile_application_id}'
    - '#/paths/~1mobile_applications~1{mobile_application_id}~1push_credentials'
    - '#/paths/~1mobile_operator_networks'
    - '#/paths/~1notification_channels'
    - '#/paths/~1notification_channels~1{id}'
    - '#/paths/~1notification_event_conditions'
    - '#/paths/~1notification_events'
    - '#/paths/~1notification_profiles'
    - '#/paths/~1notification_profiles~1{id}'
    - '#/paths/~1notification_settings'
    - '#/paths/~1notification_settings~1{id}'
    - '#/paths/~1number_block_orders'
    - '#/paths/~1number_block_orders~1{number_block_order_id}'
    - '#/paths/~1number_lookup~1{phone_number}'
    - '#/paths/~1number_order_documents'
    - '#/paths/~1number_order_documents~1{number_order_document_id}'
    - '#/paths/~1number_order_phone_numbers'
    - '#/paths/~1number_order_phone_numbers~1{number_order_phone_number_id}'
    - '#/paths/~1number_orders'
    - '#/paths/~1number_orders~1{number_order_id}'
    - '#/paths/~1number_reservations'
    - '#/paths/~1number_reservations~1{number_reservation_id}'
    - '#/paths/~1number_reservations~1{number_reservation_id}~1actions~1extend'
    - '#/paths/~1ota_updates'
    - '#/paths/~1ota_updates~1{id}'
    - '#/paths/~1outbound_voice_profiles'
    - '#/paths/~1outbound_voice_profiles~1{id}'
    - '#/paths/~1phone_number_blocks~1jobs'
    - '#/paths/~1phone_number_blocks~1jobs~1delete_phone_number_block'
    - '#/paths/~1phone_number_blocks~1jobs~1{id}'
    - '#/paths/~1phone_numbers'
    - '#/paths/~1phone_numbers~1csv_downloads'
    - '#/paths/~1phone_numbers~1csv_downloads~1{id}'
    - '#/paths/~1phone_numbers~1inbound_channels'
    - '#/paths/~1phone_numbers~1jobs'
    - '#/paths/~1phone_numbers~1jobs~1delete_phone_numbers'
    - '#/paths/~1phone_numbers~1jobs~1update_emergency_settings'
    - '#/paths/~1phone_numbers~1jobs~1update_phone_numbers'
    - '#/paths/~1phone_numbers~1jobs~1{id}'
    - '#/paths/~1phone_numbers~1messaging'
    - '#/paths/~1phone_numbers~1voice'
    - '#/paths/~1phone_numbers~1{id}'
    - '#/paths/~1phone_numbers~1{id}~1actions~1enable_emergency'
    - '#/paths/~1phone_numbers~1{id}~1messaging'
    - '#/paths/~1phone_numbers~1{id}~1voice'
    - '#/paths/~1phone_numbers_regulatory_requirements'
    - '#/paths/~1portability_checks'
    - '#/paths/~1porting_orders'
    - '#/paths/~1porting_orders~1exception_types'
    - '#/paths/~1porting_orders~1{id}'
    - '#/paths/~1porting_orders~1{id}~1actions~1activate'
    - '#/paths/~1porting_orders~1{id}~1actions~1cancel'
    - '#/paths/~1porting_orders~1{id}~1actions~1confirm'
    - '#/paths/~1porting_orders~1{id}~1activation_jobs'
    - '#/paths/~1porting_orders~1{id}~1activation_jobs~1{activationJobId}'
    - '#/paths/~1porting_orders~1{id}~1allowed_foc_windows'
    - '#/paths/~1porting_orders~1{id}~1comments'
    - '#/paths/~1porting_orders~1{id}~1documents'
    - '#/paths/~1porting_orders~1{id}~1loa_template'
    - '#/paths/~1porting_orders~1{id}~1requirements'
    - '#/paths/~1porting_orders~1{id}~1sub_request'
    - '#/paths/~1porting_phone_numbers'
    - '#/paths/~1portouts'
    - '#/paths/~1portouts~1{id}'
    - '#/paths/~1portouts~1{id}~1comments'
    - '#/paths/~1portouts~1{id}~1supporting_documents'
    - '#/paths/~1portouts~1{id}~1{status}'
    - '#/paths/~1private_wireless_gateways'
    - '#/paths/~1private_wireless_gateways~1{id}'
    - '#/paths/~1push_credentials~1{push_credential_id}'
    - '#/paths/~1queues~1{queue_name}'
    - '#/paths/~1queues~1{queue_name}~1calls'
    - '#/paths/~1queues~1{queue_name}~1calls~1{call_control_id}'
    - '#/paths/~1recordings'
    - '#/paths/~1recordings~1{id}'
    - '#/paths/~1reports~1batch_mdr_reports'
    - '#/paths/~1reports~1batch_mdr_reports~1{id}'
    - '#/paths/~1reports~1cdr_usage_reports~1sync'
    - '#/paths/~1reports~1mdr_usage_reports'
    - '#/paths/~1reports~1mdr_usage_reports~1sync'
    - '#/paths/~1reports~1mdr_usage_reports~1{id}'
    - '#/paths/~1reports~1mdrs'
    - '#/paths/~1reports~1wdrs'
    - '#/paths/~1requirement_types'
    - '#/paths/~1requirement_types~1{id}'
    - '#/paths/~1requirements'
    - '#/paths/~1requirements~1{id}'
    - '#/paths/~1room_compositions'
    - '#/paths/~1room_compositions~1{room_composition_id}'
    - '#/paths/~1room_participants'
    - '#/paths/~1room_participants~1{room_participant_id}'
    - '#/paths/~1room_recordings'
    - '#/paths/~1room_recordings~1{room_recording_id}'
    - '#/paths/~1room_sessions'
    - '#/paths/~1room_sessions~1{room_session_id}'
    - '#/paths/~1room_sessions~1{room_session_id}~1actions~1end'
    - '#/paths/~1room_sessions~1{room_session_id}~1actions~1kick'
    - '#/paths/~1room_sessions~1{room_session_id}~1actions~1mute'
    - '#/paths/~1room_sessions~1{room_session_id}~1actions~1unmute'
    - '#/paths/~1room_sessions~1{room_session_id}~1participants'
    - '#/paths/~1rooms'
    - '#/paths/~1rooms~1{room_id}'
    - '#/paths/~1rooms~1{room_id}~1actions~1generate_join_client_token'
    - '#/paths/~1rooms~1{room_id}~1actions~1refresh_client_token'
    - '#/paths/~1rooms~1{room_id}~1sessions'
    - '#/paths/~1short_codes'
    - '#/paths/~1short_codes~1{id}'
    - '#/paths/~1sim_card_actions'
    - '#/paths/~1sim_card_actions~1{id}'
    - '#/paths/~1sim_card_data_usage_notifications'
    - '#/paths/~1sim_card_data_usage_notifications~1{id}'
    - '#/paths/~1sim_card_group_actions'
    - '#/paths/~1sim_card_group_actions~1{id}'
    - '#/paths/~1sim_card_groups'
    - '#/paths/~1sim_card_groups~1{id}'
    - '#/paths/~1sim_card_groups~1{id}~1actions~1remove_private_wireless_gateway'
    - '#/paths/~1sim_card_groups~1{id}~1actions~1set_private_wireless_gateway'
    - '#/paths/~1sim_card_order_preview'
    - '#/paths/~1sim_card_orders'
    - '#/paths/~1sim_card_orders~1{id}'
    - '#/paths/~1sim_cards'
    - '#/paths/~1sim_cards~1actions~1bulk_set_public_ips'
    - '#/paths/~1sim_cards~1actions~1validate_registration_codes'
    - '#/paths/~1sim_cards~1{id}'
    - '#/paths/~1sim_cards~1{id}~1actions~1delete_network_preferences'
    - '#/paths/~1sim_cards~1{id}~1actions~1disable'
    - '#/paths/~1sim_cards~1{id}~1actions~1enable'
    - '#/paths/~1sim_cards~1{id}~1actions~1remove_public_ip'
    - '#/paths/~1sim_cards~1{id}~1actions~1set_network_preferences'
    - '#/paths/~1sim_cards~1{id}~1actions~1set_public_ip'
    - '#/paths/~1sim_cards~1{id}~1actions~1set_standby'
    - '#/paths/~1sim_cards~1{sim_card_id}~1device_details'
    - '#/paths/~1sim_cards~1{sim_card_id}~1network_preferences'
    - '#/paths/~1sim_cards~1{sim_card_id}~1public_ip'
    - '#/paths/~1sim_cards~1{sim_card_id}~1wireless_connectivity_logs'
    - '#/paths/~1sub_number_orders'
    - '#/paths/~1sub_number_orders~1{sub_number_order_id}'
    - '#/paths/~1telephony_credentials'
    - '#/paths/~1telephony_credentials~1tags'
    - '#/paths/~1telephony_credentials~1{id}'
    - '#/paths/~1telephony_credentials~1{id}~1actions~1{action}'
    - '#/paths/~1telephony_credentials~1{id}~1token'
    - '#/paths/~1texml_applications'
    - '#/paths/~1texml_applications~1{id}'
    - '#/paths/~1verifications~1whatsapp'
    - '#/paths/~1verified_calls_display_profiles'
    - '#/paths/~1verified_calls_display_profiles~1{id}'
    - '#/paths/~1verified_calls_display_profiles~1{id}~1verification_request'
    - '#/paths/~1verify_profiles'
    - '#/paths/~1verify_profiles~1{verify_profile_id}'
    - '#/paths/~1webhook_deliveries'
    - '#/paths/~1webhook_deliveries~1{id}'
    - '#/paths/~1whatsapp_business_accounts'
    - '#/paths/~1whatsapp_business_accounts~1{id}'
    - '#/paths/~1whatsapp_business_accounts~1{id}~1phone_numbers'
    - '#/paths/~1whatsapp_business_accounts~1{id}~1whatsapp_message_templates'
    - >-
      #/paths/~1whatsapp_business_accounts~1{id}~1whatsapp_message_templates~1{name}
    - '#/paths/~1whatsapp_contacts'
    - '#/paths/~1whatsapp_detail_record_reports'
    - '#/paths/~1whatsapp_detail_record_reports~1{id}'
    - '#/paths/~1whatsapp_media'
    - '#/paths/~1whatsapp_media~1{whatsapp_user_id}~1{media_id}'
    - '#/paths/~1whatsapp_messages'
    - '#/paths/~1whatsapp_messages~1{message_id}'
    - '#/paths/~1whatsapp_phone_numbers~1{id}'
    - '#/paths/~1whatsapp_phone_numbers~1{id}~1about'
    - '#/paths/~1whatsapp_phone_numbers~1{id}~1photo'
    - '#/paths/~1whatsapp_usage_aggregations'
    - '#/paths/~1wireless~1detail_records_reports'
    - '#/paths/~1wireless~1detail_records_reports~1{id}'
