properties:
  channel_limit:
    default: null
    description: >-
      When set, this will limit the total number of outbound calls to phone
      numbers associated with this connection.
    example: 10
    type: integer
  outbound_voice_profile_id:
    description: Identifies the associated outbound voice profile.
    example: '1293384261075731499'
    format: int64
    type: string
title: Call Control Application Outbound
type: object
