properties:
  channel_limit:
    default: null
    description: >-
      When set, this will limit the total number of inbound calls to phone
      numbers associated with this connection.
    example: 10
    type: integer
  sip_subdomain:
    default: null
    description: >-
      Specifies a subdomain that can be used to receive Inbound calls to a
      Connection, in the same way a phone number is used, from a SIP endpoint.
      Example: the subdomain "example.sip.telnyx.com" can be called from any SIP
      endpoint by using the SIP URI "sip:@example.sip.telnyx.com" where the user
      part can be any alphanumeric value. Please note TLS encrypted calls are
      not allowed for subdomain calls.
    example: example
    type: string
  sip_subdomain_receive_settings:
    default: from_anyone
    description: >-
      This option can be enabled to receive calls from: "Anyone" (any SIP
      endpoint in the public Internet) or "Only my connections" (any connection
      assigned to the same Telnyx user).
    enum:
      - only_my_connections
      - from_anyone
    example: only_my_connections
    type: string
title: Call Control Application Inbound
type: object
