example:
  capture_enabled: true
  port: rtcp-mux
  report_frequency_secs: 10
properties:
  capture_enabled:
    default: false
    description: >-
      BETA - Enable the capture and storage of RTCP messages to create QoS
      reports on the Telnyx Mission Control Portal.
    example: true
    type: boolean
  port:
    default: rtp+1
    description: RTCP port by default is rtp+1, it can also be set to rtcp-mux
    enum:
      - rtcp-mux
      - rtp+1
  report_frequency_secs:
    default: 5
    description: >-
      RTCP reports are sent to customers based on the frequency set. Frequency
      is in seconds and it can be set to values from 5 to 3000 seconds.
    example: 10
    type: integer
title: Connection RTCP Settings
type: object
