properties:
  application_name:
    description: Name of the appplication to be created
    example: FlashEmergency
    type: string
  type:
    description: Type of application to be created (IOS or Android)
    example: android
    type: string
required:
  - application_name
  - type
title: Create Mobile Application Request
type: object
