description: The emergency services settings for a phone number.
example:
  emergency_address_id: '1315261609962112019'
  emergency_enabled: true
properties:
  emergency_address_id:
    description: Identifies the address to be used with emergency services.
    format: int64
    type: string
  emergency_enabled:
    default: false
    description: >-
      Allows you to enable or disable emergency services on the phone number. In
      order to enable emergency services, you must also set an
      emergency_address_id.
    type: boolean
  emergency_status:
    default: disabled
    description: Represents the state of the number regarding emergency activation.
    enum:
      - disabled
      - active
      - provisioning
      - deprovisioning
    type: string
type: object
