description: >
  Number Pool allows you to send messages from a pool of numbers of different
  types, assigning

  weights to each type. The pool consists of all the long code and toll free
  numbers

  assigned to the messaging profile.


  To disable this feature, set the object field to `null`.
example:
  geomatch: false
  long_code_weight: 1
  skip_unhealthy: true
  sticky_sender: false
  toll_free_weight: 10
nullable: true
properties:
  geomatch:
    default: false
    description: >
      If set to true, Number Pool will try to choose a sending number with the
      same area code as the destination

      number. If there are no such numbers available, a nunber with a different
      area code will be chosen. Currently

      only NANP numbers are supported.
    type: boolean
  long_code_weight:
    description: >
      Defines the probability weight for a Long Code number to be selected when
      sending a message.

      The higher the weight the higher the probability. The sum of the weights
      for all number types

      does not necessarily need to add to 100.  Weight must be a non-negative
      number, and when equal

      to zero it will remove the number type from the pool.
    example: 1
    type: number
  skip_unhealthy:
    description: >
      If set to true all unhealthy numbers will be automatically excluded from
      the pool.

      Health metrics per number are calculated on a regular basis, taking into
      account the deliverability

      rate and the amount of messages marked as spam by upstream carriers.

      Numbers with a deliverability rate below 25% or spam ratio over 75% will
      be considered unhealthy.
    example: true
    type: boolean
  sticky_sender:
    default: false
    description: >
      If set to true, Number Pool will try to choose the same sending number for
      all messages to a particular

      recipient. If the sending number becomes unhealthy and `skip_unhealthy` is
      set to true, a new

      number will be chosen.
    type: boolean
  toll_free_weight:
    description: >
      Defines the probability weight for a Toll Free number to be selected when
      sending a message.

      The higher the weight the higher the probability. The sum of the weights
      for all number types

      does not necessarily need to add to 100. Weight must be a non-negative
      number, and when equal

      to zero it will remove the number type from the pool.
    example: 10
    type: number
required:
  - toll_free_weight
  - long_code_weight
  - skip_unhealthy
type: object
