example:
  emergency_address_id: '53829456729313'
  emergency_enabled: true
  phone_numbers:
    - '+19705555098'
    - '+19715555098'
    - '32873127836'
properties:
  emergency_address_id:
    description: Identifies the address to be used with emergency services.
    format: int64
    type: string
  emergency_enabled:
    description: Indicates whether to enable emergency services on this number.
    type: boolean
  phone_numbers:
    items:
      description: Array of phone number ids and/or phone numbers in E164 format to update
      type: string
    type: array
required:
  - emergency_enabled
  - emergency_address_id
  - phone_numbers
type: object
