example:
  call_forwarding:
    call_forwarding_enabled: true
    forwarding_type: always
    forwards_to: '+13035559123'
  call_recording:
    inbound_call_recording_channels: single
    inbound_call_recording_enabled: true
    inbound_call_recording_format: wav
  cnam_listing:
    cnam_listing_details: example
    cnam_listing_enabled: true
  connection_id: 1d0e6cb8-8668-462e-94c6-49ae0f0ed48b
  customer_reference: customer-reference
  emergency:
    emergency_address_id: '1315261609962112019'
    emergency_enabled: true
  id: '1293384261075731499'
  media_features:
    accept_any_rtp_packets_enabled: true
    media_handling_mode: default
    rtp_auto_adjust_enabled: true
    t38_fax_gateway_enabled: true
  record_type: voice_settings
  tech_prefix_enabled: false
  translated_number: '+13035559999'
  usage_payment_method: pay-per-minute
properties:
  call_forwarding:
    $ref: ./CallForwarding.yaml
  call_recording:
    $ref: ./CallRecording.yaml
  cnam_listing:
    $ref: ./CnamListing.yaml
  connection_id:
    description: Identifies the connection associated with this phone number.
    example: 1d0e6cb8-8668-462e-94c6-49ae0f0ed48b
    type: string
  customer_reference:
    description: A customer reference string for customer look ups.
    example: MY REF 001
    type: string
  emergency:
    $ref: ./EmergencySettings.yaml
  id:
    description: Identifies the type of resource.
    example: '1293384261075731499'
    readOnly: true
    type: string
  media_features:
    $ref: ./MediaFeatures.yaml
  phone_number:
    description: The phone number in +E164 format.
    example: '+13035551234'
    readOnly: true
    type: string
  record_type:
    description: Identifies the type of the resource.
    example: voice_settings
    readOnly: true
    type: string
  tech_prefix_enabled:
    default: false
    description: Controls whether a tech prefix is enabled for this phone number.
    example: false
    type: boolean
  translated_number:
    default: ''
    description: >-
      This field allows you to rewrite the destination number of an inbound call
      before the call is routed to you. The value of this field may be any
      alphanumeric value, and the value will replace the number originally
      dialed.
    example: '+13035559999'
    type: string
  usage_payment_method:
    default: pay-per-minute
    description: >-
      Controls whether a number is billed per minute or uses your concurrent
      channels.
    enum:
      - pay-per-minute
      - channel
    example: pay-per-minute
    type: string
type: object
