description: The settings associated with the authentication provider.
properties:
  idp_cert_fingerprint:
    description: The certificate fingerprint for the identity provider (IdP)
    example: 13:38:C7:BB:C9:FF:4A:70:38:3A:E3:D9:5C:CD:DB:2E:50:1E:80:A7
    type: string
  idp_cert_fingerprint_algorithm:
    default: sha1
    description: >-
      The algorithm used to generate the identity provider's (IdP) certificate
      fingerprint
    enum:
      - sha1
      - sha256
      - sha384
      - sha512
    example: sha256
    type: string
  idp_entity_id:
    description: The Entity ID for the identity provider (IdP).
    example: https://myorg.myidp.com/saml/metadata
    type: string
  idp_sso_target_url:
    description: The SSO target url for the identity provider (IdP).
    example: https://myorg.myidp.com/trust/saml2/http-post/sso
    type: string
required:
  - idp_entity_id
  - idp_sso_target_url
  - idp_cert_fingerprint
type: object
