example:
  active: false
  anchorsite_override: Amsterdam, Netherlands
  created_at: '2020-02-02T22:25:27.521Z'
  dtmf_type: Inband
  first_command_timeout: true
  first_command_timeout_secs: 10
  friendly_name: call-router
  id: '1293384261075731499'
  inbound:
    channel_limit: 10
    sip_subdomain: example
    sip_subdomain_receive_settings: only_my_connections
  outbound:
    channel_limit: 10
    outbound_voice_profile_id: '1293384261075731499'
  record_type: texml_application
  status_callback: https://example.com
  status_callback_method: get
  updated_at: '2020-02-03T22:25:27.521Z'
  voice_fallback_url: https://fallback.example.com
  voice_method: get
  voice_url: https://example.com
properties:
  active:
    $ref: ./ConnectionActive.yaml
  anchorsite_override:
    $ref: ./AnchorsiteOverride.yaml
  created_at:
    $ref: ./CreatedAt.yaml
  dtmf_type:
    $ref: ./DtmfType.yaml
  first_command_timeout:
    $ref: ./FirstCommandTimeout.yaml
  first_command_timeout_secs:
    $ref: ./FirstCommandTimeoutSecs.yaml
  friendly_name:
    $ref: ./ApplicationName.yaml
  id:
    $ref: ./IntId.yaml
  inbound:
    properties:
      channel_limit:
        default: null
        description: >-
          When set, this will limit the total number of inbound calls to phone
          numbers associated with this connection.
        example: 10
        type: integer
      sip_subdomain:
        default: null
        description: >-
          Specifies a subdomain that can be used to receive Inbound calls to a
          Connection, in the same way a phone number is used, from a SIP
          endpoint. Example: the subdomain "example.sip.telnyx.com" can be
          called from any SIP endpoint by using the SIP URI
          "sip:@example.sip.telnyx.com" where the user part can be any
          alphanumeric value. Please note TLS encrypted calls are not allowed
          for subdomain calls.
        example: example
        type: string
      sip_subdomain_receive_settings:
        default: from_anyone
        description: >-
          This option can be enabled to receive calls from: "Anyone" (any SIP
          endpoint in the public Internet) or "Only my connections" (any
          connection assigned to the same Telnyx user).
        enum:
          - only_my_connections
          - from_anyone
        example: only_my_connections
        type: string
    type: object
  outbound:
    properties:
      channel_limit:
        default: null
        description: >-
          When set, this will limit the total number of outbound calls to phone
          numbers associated with this connection.
        example: 10
        type: integer
      outbound_voice_profile_id:
        $ref: ./OutboundVoiceProfileId.yaml
    type: object
  record_type:
    description: Identifies the type of the resource.
    example: texml_application
    type: string
  status_callback:
    default: null
    description: >-
      URL for Telnyx to send requests to containing information about call
      progress events.
    example: https://example.com
    format: url
    type: string
  status_callback_method:
    default: post
    description: >-
      HTTP request method Telnyx should use when requesting the status_callback
      URL.
    enum:
      - get
      - post
    example: get
    type: string
  updated_at:
    $ref: ./UpdatedAt.yaml
  voice_fallback_url:
    default: null
    description: >-
      URL to which Telnyx will deliver your XML Translator webhooks if we get an
      error response from your voice_url.
    example: https://fallback.example.com
    format: url
    type: string
  voice_method:
    default: post
    description: >-
      HTTP request method Telnyx will use to interact with your XML Translator
      webhooks. Either 'get' or 'post'.
    enum:
      - get
      - post
    example: get
    type: string
  voice_url:
    description: URL to which Telnyx will deliver your XML Translator webhooks.
    example: https://example.com
    format: url
    type: string
title: Texml Application
type: object
