description: >-
  If present, applications with <code>application_name</code> containing the
  given value will be returned. Matching is not case-sensitive. Requires at
  least three characters.
in: query
name: filter[application_name][contains]
required: false
schema:
  default: 'null'
  type: string
